etl_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost             
      user: "admin"          
      password: "admin"    
      port:  5432                 
      dbname: "fin_data"   
      schema: ""                
      threads: 4  
     

