{{ config(materialized='table', schema='silver') }}

SELECT 
CAST("CODIGO" AS INT) CLIENTE,
"NOME",
TO_DATE("DATA_PRIMEIRO_VALOR_GERADO", 'DD/MM/YYYY') AS DATA_PRIMEIRO_VALOR_GERADO,
TO_DATE("DATA_ULTIMO_VALOR_GERADO", 'DD/MM/YYYY')  AS DATA_ULTIMO_VALOR_GERADO,
"FISJUR",
CAST("PRIMEIRA_FATURA_VALOR" AS FLOAT),
CAST("ULTIMA_COMPRA" AS FLOAT),
CAST("ULTIMA_FATURA_VALOR" AS FLOAT),
TO_DATE("ULTIMA_OPERACAO", 'DD/MM/YYYY') AS ULTIMA_OPERACAO
FROM {{ ref('clientes') }}


