{{ config(materialized='table', schema='silver') }}

SELECT 
CAST("CODIGO" AS INT) AS CLIENTE,
"NOME" AS NOME,
TO_DATE("DATA_PRIMEIRO_VALOR_GERADO", 'DD/MM/YYYY') AS DATA_PRIMEIRO_VALOR_GERADO,
TO_DATE("DATA_ULTIMO_VALOR_GERADO", 'DD/MM/YYYY')  AS DATA_ULTIMO_VALOR_GERADO,
"FISJUR" AS FISJUR,
CAST("PRIMEIRA_FATURA_VALOR" AS FLOAT) AS PRIMEIRA_FATURA_VALOR,
CAST("ULTIMA_COMPRA" AS FLOAT) AS ULTIMA_COMPRA,
CAST("ULTIMA_FATURA_VALOR" AS FLOAT) AS ULTIMA_FATURA_VALOR,
TO_DATE("ULTIMA_OPERACAO", 'DD/MM/YYYY') AS ULTIMA_OPERACAO
FROM {{ ref('clientes') }}


