{{ config(materialized='table', schema='silver') }}


SELECT
CAST("NUMERO" AS BIGINT) NUMERO,
"CODIGO_LOJA" as codigo_loja,
CAST("CLIENTE" AS INT) CLIENTE,
CAST("DEPARTAMENTO" AS INT)  DEPARTAMENTO,
TO_TIMESTAMP("EMISSAO", 'YYYY-MM-DD HH24:MI:SS') DTA_EMISSAO,
TO_TIMESTAMP("PAGAMENTO", 'YYYY-MM-DD HH24:MI:SS') DTA_PAGAMENTO,
"SITUACAO" as situacao,
"TIPO_DE_LANCAMENTO" as tipo_de_lancamento,
"TIPO_MOVIMENTACAO" as tipo_movimentacao,
CAST("VALOR" AS FLOAT) VALOR,
TO_TIMESTAMP("CANCELAMENTO", 'YYYY-MM-DD HH24:MI:SS') DTA_CANCELAMENTO,
TO_TIMESTAMP("VENCIMENTO", 'YYYY-MM-DD HH24:MI:SS') DTA_VENCIMENTO

FROM {{ref('titulos')}}