{{ config(materialized='table', schema='silver') }}


SELECT
CAST("NUMERO" AS BIGINT) NUMERO,
"CODIGO_LOJA",
CAST("CLIENTE" AS INT) CLIENTE,
CAST("DEPARTAMENTO" AS INT)  DEPARTAMENTO,
TO_TIMESTAMP("EMISSAO", 'YYYY-MM-DD HH24:MI:SS') DTA_EMISSAO,
TO_TIMESTAMP("PAGAMENTO", 'YYYY-MM-DD HH24:MI:SS') DTA_PAGAMENTO,
"SITUACAO",
"TIPO_DE_LANCAMENTO",
"TIPO_MOVIMENTACAO",
CAST("VALOR" AS FLOAT) VALOR,
TO_TIMESTAMP("CANCELAMENTO", 'YYYY-MM-DD HH24:MI:SS') DTA_CANCELAMENTO

FROM {{ref('titulos')}}